# https://github.com/jdx/mise#configuration
[tools]
python = {version='3.13.7'}
node = {version='24'}
"ubi:astral-sh/uv" = '0.9.17'

[settings]
experimental = true

[env]
TERRAGRUNT_TFPATH = "terraform"
_.python.venv = { path = ".venv", create = true }
