[env]
#_.python.venv = { path = ".venv", create = true }

[tools]
python = ['3.13.7']
go = ['1.25.4']
rust = 'stable'
node = '24'
uv = '0.9.10'

"npm:renovate" = "42.13.3"
"npm:prettier" = "3.6.2"
"npm:@commitlint/cli" = "20.1.0"
"npm:@devcontainers/cli" = "0.80.2"
"npm:conventional-changelog" = "7.1.1"
"npm:release-please" = "17.1.3"
"npm:@anthropic-ai/claude-code" = "2.0.43"
"npm:@openai/codex" = "0.58.0"
"npm:@github/copilot" = "0.0.359"

# pipx for cli (not library)
"pipx:pipenv" = "2025.0.4"
"pipx:poetry" = "2.2.1"
"pipx:pre-commit" = "4.4.0"
"pipx:markitdown[all]" = "0.1.3"

[settings]
experimental = true
python_compile = true
idiomatic_version_file_enable_tools = []
