[env]
#_.python.venv = { path = ".venv", create = true }

[tools]
python = ['3.14.2']
go = ['1.25.6']
rust = ['1.93.0', 'stable']
node = '24'
#"github:astral-sh/uv" = '0.9.18'
uv = '0.9.28'

"npm:renovate" = "43.0.7"
"npm:prettier" = "3.8.1"
"npm:@commitlint/cli" = "20.4.0"
"npm:@devcontainers/cli" = "0.82.0"
"npm:conventional-changelog" = "7.1.1"
"npm:release-please" = "17.2.0"
"npm:@openai/codex" = "0.94.0"
"npm:@github/copilot" = "0.0.402"

# pipx for cli (not library)
"pipx:pipenv" = "2026.0.3"
"pipx:poetry" = "2.3.1"
"pipx:pre-commit" = "4.5.1"
# "pipx:markitdown[all]" = "0.1.4"

[settings]
experimental = true
python_compile = true
idiomatic_version_file_enable_tools = []
