[env]
#_.python.venv = { path = ".venv", create = true }

[tools]
python = ['3.13.7']
go = ['1.25.5']
rust = ['1.92.0', 'stable']
node = '24'
#"github:astral-sh/uv" = '0.9.18'
uv = '0.9.22'

"npm:renovate" = "42.74.2"
"npm:prettier" = "3.7.4"
"npm:@commitlint/cli" = "20.3.1"
"npm:@devcontainers/cli" = "0.80.3"
"npm:conventional-changelog" = "7.1.1"
"npm:release-please" = "17.1.3"
"npm:@anthropic-ai/claude-code" = "2.1.1"
"npm:@openai/codex" = "0.79.0"
"npm:@github/copilot" = "0.0.375"

# pipx for cli (not library)
"pipx:pipenv" = "2026.0.3"
"pipx:poetry" = "2.2.1"
"pipx:pre-commit" = "4.5.1"
"pipx:markitdown[all]" = "0.1.4"

[settings]
experimental = true
python_compile = true
idiomatic_version_file_enable_tools = []
